In [1]:
import numpy
import math
#import matplotlib.pyplot
#import time

In [10]:
def band_m(n):
    return numpy.eye(n)*2 - numpy.eye(n, k = 1) - numpy.eye(n, k = -1)

In [17]:
A = band_m(4)
eps = 1e-6
def mxT(A, i, j, eps):
        
    n = len(A)
    T = numpy.eye(n)
    
    if A[i,i] - A[j,j] < eps:
        T[i,i] = numpy.cos(numpy.pi/4)
        T[i,j] = -numpy.sin(numpy.pi/4)
        T[j,i] = numpy.sin(numpy.pi/4)
        T[j,j] = numpy.cos(numpy.pi/4)
    else:
        tau = (A[i,i] - A[j,j])/(2*A[i,j])
        t = numpy.sign(tau)/(abs(tau) + numpy.sqrt(1 + tau**2))
        cosO = 1/numpy.sqrt(1+t**2)
        sinO = cosO*t
        
        T[i,i] = cosO
        T[i,j] = -sinO
        T[j,i] = sinO
        T[j,j] = cosO
        
    return T

def Jacobi(A, eps):
    n = len(A)
    while numpy.linalg.norm(A - numpy.diag(numpy.diag(A))) > eps:
        for i in range(0, n - 1):
            for j in range (i + 1, n):
                T = mxT(A, i, j, eps)
                A = T.T @ A @ T
    return A

print(A, "\n")       
print(Jacobi(A, eps), "\n")
print(numpy.diag(Jacobi(A,eps)), "\n")
print(numpy.linalg.eigvals(A))

[[ 2. -1.  0.  0.]
 [-1.  2. -1.  0.]
 [ 0. -1.  2. -1.]
 [ 0.  0. -1.  2.]] 

[[ 3.61803399e+00 -1.41142359e-09 -3.07057478e-14  7.51409774e-17]
 [-1.41142301e-09  2.61803399e+00  2.45111724e-17  2.64584944e-23]
 [-3.01660055e-14  1.07706733e-16  1.38196601e+00 -1.03397577e-25]
 [-2.20502987e-16 -4.78359829e-16  2.87751996e-16  3.81966011e-01]] 

[3.61803399 2.61803399 1.38196601 0.38196601] 

[3.61803399 2.61803399 0.38196601 1.38196601]
